### ISSUE TITLE
Where is the `tasks` folder?

### ISSUE THREAD

**Issue by pjdevries** [nikosdion/joomla_extensions_development#17]
**Chapter 2: Components / Integration with Scheduled Tasks** contains the phrase "You create a plugin which provides one or more scheduled tasks in the `tasks` folder". I searched for that folder in a Joomla! 4.2.4 installation with ATS Core installed, but could only find a subfolder by that name in `.../administrator/components/com_scheduler/tmpl`. I guess that's not the one being referred to. If not, which one is?

**Comment by nikosdion** [comment]
Plugin folders are under the `plugins` folder in your site's root.

Joomla 4.2 already comes with plugins in the `plugins/task` folder.

I fixed the typo (final "s").
