### ISSUE TITLE
Duplicate content about language files

### ISSUE THREAD

**Issue by pjdevries** [nikosdion/joomla_extensions_development#19]
First of all, I want to thank you for this book, this fantastic reference work, which I neglected to do until now. It is an incredibly valuable piece of work and greatly appreciated by yours truly.

I know it's a work in progress, so maybe this next suggestion is a bit premature.

The section about language files in the plugins chapter contains a lot of information already contained in the language files section of the components chapter. I also see an upcoming language files section in the modules chapter. May I suggest to create a specific language file specific section, containing all the general information about language files and only include the extension type specific bits in the extension specific chapters? Nice and DRY :D

**Comment by nikosdion** [comment]
I originally thought about doing exactly that, but I realised that the book is unlikely to be read serially. Moreover, there are subtle differences between the language files of components, plugins, and modules. Even the system language files are not loaded in the same context.

I'd rather duplicate some information in the book than confuse someone or give them the wrong idea. I am pretty sure some people reading it will not be experienced Joomla developers. Maybe someone was making modules and decided to try their hand at a small plugin or a component.
