### ISSUE TITLE
500 Error when trying to open any Links on the HTML page for this Book.

### ISSUE THREAD

**Issue by Irata** [nikosdion/joomla_extensions_development#23]
When attempting o open any of the links on the HTML copy of this book, https://www.dionysopoulos.me/book.html, results in Server issuing a HTML  Error 500. This is just one of the links where the issue is happening, https://www.dionysopoulos.me/book/concepts-container.html

I have tried the link under a different browser, Google Chrome, and the same problem occurs, t has probably been a coupe of weeks since I last used the book but it was fine then.

**Comment by nikosdion** [comment]
I was missing a colon in a template override. Try again now, it will work.
