### ISSUE TITLE
Possible mistake on page "Pushing dependencies to the Router"

### ISSUE THREAD

**Issue by pjdevries** [nikosdion/joomla_extensions_development#28]
The bottom of page [Pushing dependencies to the Router ](https://www.dionysopoulos.me/book/com-router-push-dependencies.html) shows the following code:

```
$container->registerServiceProvider(
  new \Acme\Component\Example\Administrator\Service\Provider\RouterFactoryProvider(
    '\\Acme\\Example'
  )
);
```

It appears to me that the `\\Component` segment is missing from the `RouterFactoryProvider::constuct()` namespace parameter. Shouldn't it be:
```
$container->registerServiceProvider(
  new \Acme\Component\Example\Administrator\Service\Provider\RouterFactoryProvider(
    '\\Acme\\Component\\Example'
  )
);
```?

**Comment by nikosdion** [comment]
Yes, that's missing. Can you please do a PR?
