### ISSUE TITLE
windows: can not create pdf: .... Variable 'writing.mode' has not been declared.

### ISSUE THREAD

**Issue by ThomasFinnern** [nikosdion/joomla_extensions_development#31]
**Describe what's wrong**
Installed [XMLMind DocBook Editor](https://www.xmlmind.com/xmleditor/docbook_editor.html), 
Adapted the command to use the XMLmind_XML_Editor ... chunkfast.xsl file.
This did create a set of html files.  Then i tried to use the html.xsl instead

`xsltproc --nonet --xinclude --novalid --stringparam body.start.indent 0 --stringparam variablelist.term.break.after 1  --stringparam variablelist.term.separator "" --stringparam variablelist.max.termlength 12 --stringparam section.autolabel 1 --stringparam toc.section.depth 5 --stringparam base.dir /var/www/html/jextdev "c:\Program Files (x86)\XMLmind_XML_Editor\addon\config\docbook5\xsl\html\html.xsl"  joomla_extensions_development.xml`

This leads to the error message

`runtime error: file file:/c:/Program%20Files%20(x86)/XMLmind_DocBook_Editor/addon/config/docbook5/xsl/html/html.xsl line 29 element choose
Variable 'writing.mode' has not been declared.`

**Reasoning**
googled for solution but only found a hint that 

> html.xsl is not supposed to be called that way. It's part of the html/docbook.xsl includeset. You shouldn't call it directly

[xsltproc parse error](https://bugs.archlinux.org/task/19446)

**Suggestion**
%

**Comment by nikosdion** [comment]
This is really not an issue for this repository.

As you already established, you need to use `"c:\Program Files (x86)\XMLmind_XML_Editor\addon\config\docbook5\xsl\html\docbook.xsl"` instead of `"c:\Program Files (x86)\XMLmind_XML_Editor\addon\config\docbook5\xsl\html\html.xsl"`.

**Comment by ThomasFinnern** [comment]
> This is really not an issue for this repository

It is told in the readme how it shall work and i get an error. Which place would be the right one to mention it ?

Using the .../html.xls command i get metioned error, which is still mentioned in the readme od this repository . i will try docbook.xsl now

**Comment by nikosdion** [comment]
Okay, now I understand the context. The way you had worded it above sounded like you wanted help with the DocBook XSL Stylesheets which is beyond the scope of this repository. Yes, I'll correct the README.
