### ISSUE TITLE
plugin description "handleFoobar" code is interupted with new code starting "<?php namespace Acme\Plugin\System\Example; ...

### ISSUE THREAD

**Issue by ThomasFinnern** [nikosdion/joomla_extensions_development#33]
**Describe what's wrong**
Section "Handling concrete events" shows a function "public function handleFoobar(Event $event)" 
whre in the middle of the code starts a different "code file "

see repository 
https://github.com/nikosdion/joomla_extensions_development/blob/main/sections/plugins.xml
In line 1841++ starts a different code within function

**Reasoning**
%

**Suggestion**
%

**Comment by nikosdion** [comment]
Thank you!
